### ISSUE TITLE
Rewrite in Go

### ISSUE THREAD

**Issue by tuana9a** [tuana9a/kp#1]
Write in Go... Write in Go... Can't go back anymore...

https://github.com/spf13/cobra

# Tasks

- [x] kubeadm
  - [x] reset
- [ ] plane
  - [ ] alone
    - [ ] create
    - [ ] delete
  - [x] child
    - [x] create
    - [x] delete
    - [ ] ~~firstupgrade~~ should be performed manually
    - [ ] ~~followupupgrade~~ should be performed manually
    - [x] join
  - [ ] dad
    - [ ] ~~create_join_command~~ included in join operation
    - [x] create
    - [ ] ~~distribute_certs~~ included in join operation
    - [ ] init
  - [x] etcd
    - [x] endpoint
      - [x] status
    - [x] member
      - [x] list
      - [x] remove
    - [ ] ~~snapshot~~ not needed
      - [ ] ~~save~~ not needed
  - [ ] ~~kubeconfig~~ not needed
    - [ ] ~~download~~ not needed
    - [ ] ~~view~~ not needed
  - [x] kubevip
    - [x] install
    - [x] uninstall
  - [ ] ~~backup~~ this action should be performed manually or by cronjob
  - [ ] ~~restore~~ this action should be performed manually
- [x] vm
  - [x] agent
    - [x] wait
  - [x] cloudinit
    - [x] wait
  - [x] userdata
    - [x] run
  - [x] clone
  - [ ] ~~reboot~~ = shutdown + start
  - [x] remove
  - [ ] scp
  - [x] shutdown
  - [x] start
  - [x] update_config
- [x] worker
  - [x] create
  - [x] delete
  - [x] join
  - [ ] ~~upgrade~~ not needed

**Comment by tuana9a** [comment]
well I think this can be considered completed. the init part is something really important that will be implemented later.
